// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://bgghkwvqtpnsgdpqzrqz.supabase.co";
const SUPABASE_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ2hrd3ZxdHBuc2dkcHF6cnF6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mjg0MTg5MywiZXhwIjoyMDg4NDE3ODkzfQ.DIoMdD40IDBJcd1K0FkVYeCAKZRS0QRDdkq8WnNC9Zs"
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZ2hrd3ZxdHBuc2dkcHF6cnF6Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Mjg0MTg5MywiZXhwIjoyMDg4NDE3ODkzfQ.DIoMdD40IDBJcd1K0FkVYeCAKZRS0QRDdkq8WnNC9Zs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);